import '../globals.css';
import type { Metadata } from 'next';
import { inter } from '../fonts';
import Navbar from '../_components/navigation/navbar';
import Footer from '../_components/navigation/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
